### ISSUE TITLE
auto_trim.sh not running due to syntax 

### ISSUE THREAD

**Issue by dlegend116** [lakhujanivijay/Shell_scripts#1]
I am having an issue running the .sh, I get error with this message `auto_trim.sh: 64: auto_trim.sh: Syntax error: word unexpected (expecting ")")`

**Comment by lakhujanivijay** [comment]
Hi

Could you please try downloading the file again from [here](https://github.com/lakhujanivijay/I-Shell-Do-This/blob/master/automation_of_trimmomatic/auto_trim.sh) and run as 'source auto_trim.sh' ?

**Comment by lakhujanivijay** [comment]
@dlegend116 Let me know if the problem is already solved.
